name: audio-processing
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1=h7bae524_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h6a3b0d2_0
  - dav1d=1.2.1=hb547adb_0
  - expat=2.7.3=h982b769_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - gdk-pixbuf=2.42.10=h969f7ef_2
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - glib=2.84.4=h863a760_0
  - glib-tools=2.84.4=hff4a405_0
  - gmp=6.3.0=h7bae524_2
  - gnutls=3.6.15=h887c41c_0
  - graphite2=1.3.14=hec049ff_2
  - harfbuzz=11.4.5=hf4e55d4_0
  - icu=75.1=hfee45f7_0
  - jpeg=9f=h2f69dba_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libass=0.17.3=h68e5b86_2
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libglib=2.84.4=h7a3292d_0
  - libhwloc=2.11.2=default_hbce5d74_1001
  - libiconv=1.18=h23cfdf5_2
  - libidn2=2.3.4=h80987f9_0
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libopenjpeg=2.5.4=haa24f5a_1
  - libopenvino=2024.4.0=hbfeda7a_2
  - libopenvino-arm-cpu-plugin=2024.4.0=hbfeda7a_2
  - libopenvino-auto-batch-plugin=2024.4.0=hf276634_2
  - libopenvino-auto-plugin=2024.4.0=hf276634_2
  - libopenvino-hetero-plugin=2024.4.0=h03892cd_2
  - libopenvino-ir-frontend=2024.4.0=h03892cd_2
  - libopenvino-onnx-frontend=2024.4.0=h7f5a098_2
  - libopenvino-paddle-frontend=2024.4.0=h7f5a098_2
  - libopenvino-pytorch-frontend=2024.4.0=h5833ebf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h9d544f2_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5833ebf_2
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.51=hfab5511_0
  - libprotobuf=5.28.2=h8f0b736_0
  - libtasn1=4.20.0=h25138cc_0
  - libtiff=4.7.1=h367c460_0
  - libunistring=0.9.10=h1a28f6b_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxml2=2.13.5=hbbdcc80_0
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - nettle=3.7.3=h84b5d62_1
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.5.4=h959fc53_1
  - openssl=3.6.0=h5503f6c_0
  - pango=1.56.4=h875632e_0
  - pcre2=10.46=h7125dd6_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h81086ad_1
  - pugixml=1.14=h13dd4ca_0
  - python=3.9.25=he39995d_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py39hca03da5_0
  - snappy=1.2.2=hada39a4_1
  - sqlite=3.51.0=hab6afd1_0
  - svt-av1=2.3.0=hf24288c_0
  - tbb=2022.1.0=h9541205_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39hca03da5_0
  - x264=1!152.20180806=h1a28f6b_0
  - x265=3.5=hbc6ce65_3
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - audioread==3.1.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - ffmpeg==1.4
      - fonttools==4.60.1
      - idna==3.11
      - importlib-resources==6.5.2
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.43.0
      - matplotlib==3.9.4
      - msgpack==1.1.2
      - numba==0.60.0
      - numpy==2.0.2
      - packaging==25.0
      - pedalboard==0.9.17
      - pillow==11.3.0
      - platformdirs==4.4.0
      - pooch==1.8.2
      - pycparser==2.23
      - pydub==0.25.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - requests==2.32.5
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.17.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - zipp==3.23.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/audio-processing
